# hydra.job.chdir: false
hydra:
  searchpath:
    # see https://hydra.cc/docs/advanced/search_path/
    - file:///home/p/下载/WheelLeg/cfg

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 150_000_000
max_iters: -1
eval_interval: -1
save_interval: -1
seed: 0
checkpoint_version: v1

tensorboard:
  enabled: false
  log_dir: /home/p/下载/WheelLeg/tb_runs

keyboard_control: false
teleop_speed: 0.07
teleop_smoothing: 0.12
teleop_command_file: /tmp/twowheel_cmd.txt

viewer:
  resolution: [960, 720]
  eye: [8, 0., 6.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}-${oc.select:..algo.name,none}
  job_type: train
  entity:
  project: omnidrones
  mode: disabled
  run_id:
  monitor_gym: True
  tags:

defaults:
  - task: TwoWheelBalance
  - algo: ppo
  - _self_
